language: node_js
cache:
  directories:
  - "node_modules"
node_js:
- 8
before_script:
- npm install -g markdownlint-cli
script:
- markdownlint --config $TRAVIS_BUILD_DIR/.markdownlint.json README.md
